vaultwarden:
  dns:
    enabled: true
    domain_name: "vault.dcapi.app"
  network:
    internal: true
    service_port: 80
    networks:
      - name: "br1"
        ip_address: "192.168.4.201"
  auth:
    enabled: false
  secrets:
    ADMIN_TOKEN: "VAULTWARDEN_ADMIN_TOKEN"
  service_name: "vaultwarden"
  image_name: "vaultwarden/server:1.34.1"
  mounts:
    - "/mnt/user/appdata/vaultwarden:/data"
  env:
    - "TZ=America/Los_Angeles"
    - "INVITATIONS_ALLOWED=true"
    - "SIGNUPS_ALLOWED=false"
    - "WEBSOCKET_ENABLED=true"
